# Generated by Django 5.0.1 on 2025-11-30 15:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_age",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(18)]
                    ),
                ),
                (
                    "retirement_age",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(18)]
                    ),
                ),
                (
                    "life_expectancy",
                    models.IntegerField(
                        default=95,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "annual_spending",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "social_security_annual",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "pension_annual",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "current_portfolio_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Financial Profile",
                "verbose_name_plural": "Financial Profiles",
                "db_table": "financial_profile",
            },
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("stock", "Stocks"),
                            ("bond", "Bonds"),
                            ("real_estate", "Real Estate"),
                            ("retirement_account", "Retirement Account"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("current_value", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "annual_return_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.07,
                        help_text="Expected annual return (e.g., 0.07 for 7%)",
                        max_digits=5,
                    ),
                ),
                (
                    "allocation_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Percentage of total portfolio",
                        max_digits=5,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset",
                "verbose_name_plural": "Assets",
                "db_table": "asset",
                "indexes": [
                    models.Index(fields=["user"], name="asset_user_id_bcef9f_idx"),
                    models.Index(
                        fields=["asset_type"], name="asset_asset_t_0df6bb_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "expense_type",
                    models.CharField(
                        choices=[
                            ("housing", "Housing"),
                            ("utilities", "Utilities"),
                            ("food", "Food"),
                            ("transportation", "Transportation"),
                            ("healthcare", "Healthcare"),
                            ("insurance", "Insurance"),
                            ("entertainment", "Entertainment"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("annual", "Annual"),
                            ("one_time", "One Time"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                (
                    "start_age",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(18)],
                    ),
                ),
                (
                    "end_age",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(18)],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Expense",
                "verbose_name_plural": "Expenses",
                "db_table": "expense",
                "indexes": [
                    models.Index(fields=["user"], name="expense_user_id_2c0bb9_idx"),
                    models.Index(
                        fields=["expense_type"], name="expense_expense_38f45d_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="IncomeSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "income_type",
                    models.CharField(
                        choices=[
                            ("salary", "Salary"),
                            ("social_security", "Social Security"),
                            ("pension", "Pension"),
                            ("rental_income", "Rental Income"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("annual_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "start_age",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(18)],
                    ),
                ),
                (
                    "end_age",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(18)],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="income_sources",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Income Source",
                "verbose_name_plural": "Income Sources",
                "db_table": "income_source",
                "indexes": [
                    models.Index(
                        fields=["user"], name="income_sour_user_id_3a0ea0_idx"
                    ),
                    models.Index(
                        fields=["income_type"], name="income_sour_income__92a49e_idx"
                    ),
                ],
            },
        ),
    ]
