# Generated by Django 5.0.1 on 2025-12-03 19:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialprofile",
            name="current_age",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(18)],
            ),
        ),
        migrations.AlterField(
            model_name="financialprofile",
            name="retirement_age",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(18)],
            ),
        ),
    ]
