# Generated by Django 5.0.1 on 2025-12-07 18:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0002_convert_age_fields_to_decimal"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="My Portfolio", max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Portfolio",
                "verbose_name_plural": "Portfolios",
                "db_table": "portfolio",
            },
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("trad_401k", "Traditional 401(k)"),
                            ("roth_401k", "Roth 401(k)"),
                            ("trad_ira", "Traditional IRA"),
                            ("roth_ira", "Roth IRA"),
                            ("sep_ira", "SEP IRA"),
                            ("solo_401k", "Solo 401(k)"),
                            ("taxable_brokerage", "Taxable Brokerage"),
                            ("joint_account", "Joint Investment Account"),
                            ("partnership", "Partnership Account"),
                            ("savings", "Savings Account"),
                            ("hysa", "High-Yield Savings Account"),
                            ("money_market", "Money Market Account"),
                            ("hsa", "Health Savings Account"),
                            ("msa", "Medical Savings Account"),
                            ("529_plan", "College 529 Plan"),
                            ("certificate_cd", "Certificate of Deposit"),
                            ("bonds", "Bonds"),
                            ("treasuries", "Treasury Securities"),
                            ("custom", "Custom Account Type"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "account_name",
                    models.CharField(
                        help_text="User-friendly account name", max_length=255
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        blank=True,
                        help_text="Account reference/number",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "institution_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "current_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "default_growth_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.07"),
                        help_text="Annual % return (e.g., 0.07 for 7%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-1.00")),
                            django.core.validators.MaxValueValidator(Decimal("10.00")),
                        ],
                    ),
                ),
                (
                    "inflation_adjustment",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.00"),
                        help_text="Inflation adjustment applied to growth rate",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("1.00")),
                        ],
                    ),
                ),
                (
                    "expected_contribution_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.00"),
                        help_text="Expected annual contributions as % of current value",
                        max_digits=5,
                    ),
                ),
                (
                    "investment_allocation",
                    models.JSONField(
                        default=dict,
                        help_text='Investment allocation: {"stocks": 60, "bonds": 30, "other": 10}',
                    ),
                ),
                (
                    "withdrawal_priority",
                    models.IntegerField(
                        default=0,
                        help_text="Order to withdraw from this account (lower = first)",
                    ),
                ),
                (
                    "withdrawal_restrictions",
                    models.JSONField(
                        default=dict,
                        help_text='Withdrawal restrictions: {"min_age": 59.5, "penalty_free_date": "2030-01-01"}',
                    ),
                ),
                (
                    "tax_treatment",
                    models.CharField(
                        choices=[
                            ("pre_tax", "Pre-Tax"),
                            ("post_tax", "Post-Tax"),
                            ("tax_exempt", "Tax-Exempt"),
                        ],
                        default="pre_tax",
                        max_length=20,
                    ),
                ),
                (
                    "rmd_age",
                    models.IntegerField(
                        default=72,
                        help_text="Age at which RMD begins",
                        validators=[
                            django.core.validators.MinValueValidator(50),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "rmd_percentage",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.00"),
                        help_text="RMD percentage (calculated as 1/life_expectancy_divisor)",
                        max_digits=5,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("closed", "Closed"),
                            ("merged", "Merged"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "data_source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Entry"),
                            ("import", "CSV Import"),
                            ("api", "API Sync"),
                        ],
                        default="manual",
                        max_length=50,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to="financial.portfolio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Account",
                "verbose_name_plural": "Accounts",
                "db_table": "account",
                "ordering": ["withdrawal_priority", "account_name"],
            },
        ),
        migrations.CreateModel(
            name="PortfolioSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("snapshot_date", models.DateField(help_text="Date of the snapshot")),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "calculated_from",
                    models.CharField(
                        choices=[
                            ("all_accounts", "All Accounts"),
                            ("last_snapshot", "Last Snapshot"),
                        ],
                        default="all_accounts",
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="financial.portfolio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Portfolio Snapshot",
                "verbose_name_plural": "Portfolio Snapshots",
                "db_table": "portfolio_snapshot",
                "ordering": ["-snapshot_date"],
            },
        ),
        migrations.CreateModel(
            name="AccountValueHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "recorded_date",
                    models.DateField(help_text="Date the value snapshot was recorded"),
                ),
                ("recorded_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Entry"),
                            ("import", "CSV Import"),
                            ("system", "System Generated"),
                        ],
                        default="manual",
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="value_history",
                        to="financial.account",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="account_history_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Account Value History",
                "verbose_name_plural": "Account Value History",
                "db_table": "account_value_history",
                "ordering": ["-recorded_date"],
                "indexes": [
                    models.Index(
                        fields=["account"], name="account_val_account_c796a4_idx"
                    ),
                    models.Index(
                        fields=["recorded_date"], name="account_val_recorde_559b05_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(fields=["portfolio"], name="account_portfol_aa6cea_idx"),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["account_type"], name="account_account_1922e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(fields=["status"], name="account_status_a9dc5b_idx"),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["withdrawal_priority"], name="account_withdra_2b4c0b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="portfoliosnapshot",
            index=models.Index(
                fields=["portfolio"], name="portfolio_s_portfol_65062c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="portfoliosnapshot",
            index=models.Index(
                fields=["snapshot_date"], name="portfolio_s_snapsho_b01cce_idx"
            ),
        ),
    ]
