# Generated by Django 5.0.1 on 2025-12-17 16:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0003_add_portfolio_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="default_growth_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.07"),
                help_text="Annual % return (e.g., 0.07 for 7%)",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("-1.00")),
                    django.core.validators.MaxValueValidator(Decimal("1.00")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="inflation_adjustment",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.00"),
                help_text="Inflation adjustment applied to growth rate (0.03 = 3%)",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("1.00")),
                ],
            ),
        ),
        migrations.CreateModel(
            name="TaxProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "filing_status",
                    models.CharField(
                        choices=[
                            ("single", "Single"),
                            ("mfj", "Married Filing Jointly"),
                            ("mfs", "Married Filing Separately"),
                            ("hoh", "Head of Household"),
                            ("qw", "Qualifying Widow(er)"),
                        ],
                        default="single",
                        max_length=10,
                    ),
                ),
                (
                    "state_of_residence",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="State of residence for state income tax calculations",
                        max_length=50,
                    ),
                ),
                (
                    "full_retirement_age",
                    models.IntegerField(
                        default=67,
                        help_text="Full Retirement Age for Social Security calculations",
                    ),
                ),
                (
                    "social_security_age_62",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Monthly Social Security benefit if claiming at age 62",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "social_security_age_65",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Monthly Social Security benefit if claiming at age 65",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "social_security_age_67",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Monthly Social Security benefit if claiming at age 67 (Full Retirement Age)",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "social_security_age_70",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Monthly Social Security benefit if claiming at age 70",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "traditional_ira_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Traditional IRA balance (pre-tax account)",
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "roth_ira_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Roth IRA balance (post-tax account, tax-free growth)",
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "taxable_account_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Taxable brokerage account balance",
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "hsa_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Health Savings Account balance",
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "pension_annual",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Expected annual pension income",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tax Profile",
                "verbose_name_plural": "Tax Profiles",
                "db_table": "tax_profile",
            },
        ),
    ]
