# Generated by Django 5.0.1 on 2025-12-17 20:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0004_alter_account_default_growth_rate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialprofile",
            name="pension_start_age",
            field=models.IntegerField(
                blank=True,
                default=65,
                null=True,
                validators=[django.core.validators.MinValueValidator(18)],
            ),
        ),
    ]
