# Generated by Django 5.0.1 on 2025-12-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0005_financialprofile_pension_start_age"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taxprofile",
            name="full_retirement_age",
        ),
        migrations.RemoveField(
            model_name="taxprofile",
            name="hsa_balance",
        ),
        migrations.RemoveField(
            model_name="taxprofile",
            name="pension_annual",
        ),
        migrations.RemoveField(
            model_name="taxprofile",
            name="roth_ira_balance",
        ),
        migrations.RemoveField(
            model_name="taxprofile",
            name="social_security_age_62",
        ),
        migrations.RemoveField(
            model_name="taxprofile",
            name="social_security_age_65",
        ),
        migrations.RemoveField(
            model_name="taxprofile",
            name="social_security_age_67",
        ),
        migrations.RemoveField(
            model_name="taxprofile",
            name="social_security_age_70",
        ),
        migrations.RemoveField(
            model_name="taxprofile",
            name="taxable_account_balance",
        ),
        migrations.RemoveField(
            model_name="taxprofile",
            name="traditional_ira_balance",
        ),
        migrations.AlterField(
            model_name="taxprofile",
            name="filing_status",
            field=models.CharField(
                choices=[
                    ("single", "Single"),
                    ("mfj", "Married Filing Jointly"),
                    ("mfs", "Married Filing Separately"),
                    ("hoh", "Head of Household"),
                    ("qw", "Qualifying Widow(er)"),
                ],
                default="single",
                help_text="Tax filing status for federal income tax calculations",
                max_length=10,
            ),
        ),
    ]
