# Generated by Django 5.0.1 on 2025-12-24 16:36

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0006_remove_redundant_tax_profile_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxprofile",
            name="social_security_age_62",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Estimated monthly Social Security benefit if claimed at age 62 (~70% of FRA)",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="taxprofile",
            name="social_security_age_65",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Estimated monthly Social Security benefit if claimed at age 65 (~86% of FRA)",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="taxprofile",
            name="social_security_age_67",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Estimated monthly Social Security benefit if claimed at age 67 (100% - Full Retirement Age)",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="taxprofile",
            name="social_security_age_70",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Estimated monthly Social Security benefit if claimed at age 70 (~124% of FRA with delayed credits)",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
    ]
