# Generated by Django 5.0.1 on 2025-12-24 20:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0007_taxprofile_social_security_age_62_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taxprofile",
            name="social_security_age_62",
            field=models.IntegerField(
                default=0,
                help_text="Estimated monthly Social Security benefit if claimed at age 62 (~70% of FRA)",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="taxprofile",
            name="social_security_age_65",
            field=models.IntegerField(
                default=0,
                help_text="Estimated monthly Social Security benefit if claimed at age 65 (~86% of FRA)",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="taxprofile",
            name="social_security_age_67",
            field=models.IntegerField(
                default=0,
                help_text="Estimated monthly Social Security benefit if claimed at age 67 (100% - Full Retirement Age)",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="taxprofile",
            name="social_security_age_70",
            field=models.IntegerField(
                default=0,
                help_text="Estimated monthly Social Security benefit if claimed at age 70 (~124% of FRA with delayed credits)",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
