apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
  namespace: monitoring
spec:
  mode: deployment
  image: otel/opentelemetry-collector-contrib:latest
  env:
    - name: SPLUNK_HEC_TOKEN
      valueFrom:
        secretKeyRef:
          name: otel-collector-secrets
          key: SPLUNK_HEC_TOKEN
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:4318"
      filelog:
        include:
          - /var/log/containers/*jretirewise*.log
          - /var/log/containers/*todo*.log
          - /var/log/containers/*emporia*.log
        exclude:
          - /var/log/containers/*_kube-system_*.log
          - /var/log/containers/*_kube-public_*.log
          - /var/log/containers/*_kube-node-lease_*.log
        multiline:
          line_start_pattern: '^\{'
        operators:
          - type: json_parser
            timestamp:
              parse_from: attributes.asctime
              layout: '%Y-%m-%d %H:%M:%S,%f'
            severity:
              parse_from: attributes.levelname
    processors:
      batch:
        send_batch_size: 100
        timeout: 10s
      attributes:
        actions:
          - key: environment
            value: production
            action: insert
          - key: cluster
            value: home-lab
            action: insert
      resourcedetection:
        detectors:
          - env
        override: false
        timeout: 5s
    exporters:
      prometheus:
        endpoint: "0.0.0.0:8890"
      otlp:
        endpoint: "tempo.monitoring.svc.cluster.local:4317"
        tls:
          insecure: true
      splunk_hec:
        token: "${SPLUNK_HEC_TOKEN}"
        endpoint: "https://splunk.splunk.svc.cluster.local:8088/services/collector"
        source: "otel"
        sourcetype: "otel:logs"
        index: "otel_logging"
        disable_compression: false
        timeout: 10s
        tls:
          insecure_skip_verify: true
      debug:
        verbosity: detailed
    service:
      telemetry:
        logs:
          level: "debug"
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheus]
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
        logs:
          receivers: [otlp, filelog]
          processors: [batch, attributes]
          exporters: [splunk_hec, debug]
  volumes:
    - name: splunk-secret
      secret:
        secretName: otel-collector-secrets
    - name: varlog
      hostPath:
        path: /var/log
    - name: varlibdockercontainers
      hostPath:
        path: /var/lib/docker/containers
  volumeMounts:
    - name: splunk-secret
      mountPath: /etc/otel/secrets
      readOnly: true
    - name: varlog
      mountPath: /var/log
      readOnly: true
    - name: varlibdockercontainers
      mountPath: /var/lib/docker/containers
      readOnly: true
