# Generated by Django 5.0.1 on 2025-11-30 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RetirementScenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "calculator_type",
                    models.CharField(
                        choices=[
                            ("4_percent", "4% Rule"),
                            ("4_7_percent", "4.7% Rule"),
                            ("monte_carlo", "Monte Carlo"),
                            ("historical", "Historical Analysis"),
                        ],
                        max_length=50,
                    ),
                ),
                ("parameters", models.JSONField(default=dict)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scenarios",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Retirement Scenario",
                "verbose_name_plural": "Retirement Scenarios",
                "db_table": "scenario",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="CalculationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("result_data", models.JSONField(default=dict)),
                ("execution_time_ms", models.IntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scenario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="scenarios.retirementscenario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Calculation Result",
                "verbose_name_plural": "Calculation Results",
                "db_table": "calculation_result",
            },
        ),
        migrations.AddIndex(
            model_name="retirementscenario",
            index=models.Index(fields=["user"], name="scenario_user_id_da51ed_idx"),
        ),
        migrations.AddIndex(
            model_name="retirementscenario",
            index=models.Index(
                fields=["calculator_type"], name="scenario_calcula_a47bbf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="calculationresult",
            index=models.Index(
                fields=["scenario"], name="calculation_scenari_f581b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="calculationresult",
            index=models.Index(fields=["status"], name="calculation_status_552762_idx"),
        ),
    ]
