# Generated by Django 5.0.1 on 2025-12-09 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scenarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="retirementscenario",
            name="calculator_type",
            field=models.CharField(
                choices=[
                    ("4_percent", "4% Rule"),
                    ("4_7_percent", "4.7% Rule"),
                    ("bucketed_withdrawal", "Bucketed Withdrawal"),
                    ("monte_carlo", "Monte Carlo"),
                    ("historical", "Historical Analysis"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="WithdrawalBucket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bucket_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("order", models.IntegerField(default=0)),
                ("start_age", models.IntegerField(blank=True, null=True)),
                ("end_age", models.IntegerField(blank=True, null=True)),
                ("start_year", models.IntegerField(blank=True, null=True)),
                ("end_year", models.IntegerField(blank=True, null=True)),
                (
                    "target_withdrawal_rate",
                    models.FloatField(
                        help_text="Percentage of portfolio (e.g., 4.0 for 4%)"
                    ),
                ),
                (
                    "min_withdrawal_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum withdrawal amount in dollars",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "max_withdrawal_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum withdrawal amount in dollars",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "manual_withdrawal_override",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Fixed withdrawal amount if set (overrides rate calculation)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "allowed_account_types",
                    models.JSONField(
                        default=list,
                        help_text="List of allowed account type codes (e.g., ['traditional_401k', 'roth_ira'])",
                    ),
                ),
                (
                    "prohibited_account_types",
                    models.JSONField(
                        default=list, help_text="List of prohibited account type codes"
                    ),
                ),
                (
                    "withdrawal_order",
                    models.JSONField(
                        default=list,
                        help_text="Ordered list of account IDs for withdrawal preference",
                    ),
                ),
                ("tax_loss_harvesting_enabled", models.BooleanField(default=False)),
                ("roth_conversion_enabled", models.BooleanField(default=False)),
                (
                    "healthcare_cost_adjustment",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Healthcare cost adjustment in dollars (positive increases withdrawal need)",
                        max_digits=12,
                    ),
                ),
                (
                    "expected_pension_income",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Expected pension income per year (reduces portfolio withdrawal need)",
                        max_digits=12,
                    ),
                ),
                (
                    "expected_social_security_income",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Expected Social Security income per year (reduces portfolio withdrawal need)",
                        max_digits=12,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawal_buckets",
                        to="scenarios.retirementscenario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Withdrawal Bucket",
                "verbose_name_plural": "Withdrawal Buckets",
                "db_table": "withdrawal_bucket",
                "ordering": ["order", "start_age"],
            },
        ),
        migrations.CreateModel(
            name="BucketedWithdrawalResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("age", models.IntegerField(blank=True, null=True)),
                (
                    "target_rate",
                    models.FloatField(
                        help_text="Target withdrawal rate for this year (%)"
                    ),
                ),
                (
                    "calculated_withdrawal",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Calculated withdrawal based on rate and portfolio value",
                        max_digits=12,
                    ),
                ),
                (
                    "actual_withdrawal",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Actual withdrawal amount (may differ due to constraints)",
                        max_digits=12,
                    ),
                ),
                (
                    "withdrawal_accounts",
                    models.JSONField(
                        default=dict,
                        help_text="Account-by-account withdrawal breakdown: {account_id: amount}",
                    ),
                ),
                (
                    "portfolio_value_start",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Portfolio value at start of year",
                        max_digits=12,
                    ),
                ),
                (
                    "investment_growth",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Investment growth/returns during year",
                        max_digits=12,
                    ),
                ),
                (
                    "portfolio_value_end",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Portfolio value at end of year after withdrawal",
                        max_digits=12,
                    ),
                ),
                (
                    "pension_income",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Pension income during year",
                        max_digits=12,
                    ),
                ),
                (
                    "social_security_income",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Social Security income during year",
                        max_digits=12,
                    ),
                ),
                (
                    "total_available_income",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total available income (withdrawal + pension + SS)",
                        max_digits=12,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes about this year (RMD applied, early access penalty, etc.)",
                    ),
                ),
                (
                    "flags",
                    models.JSONField(
                        default=list,
                        help_text="Array of warning flags: ['rmd_applied', 'early_access_penalty', etc.]",
                    ),
                ),
                (
                    "calculation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bucketed_results",
                        to="scenarios.calculationresult",
                    ),
                ),
                (
                    "bucket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="results",
                        to="scenarios.withdrawalbucket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bucketed Withdrawal Result",
                "verbose_name_plural": "Bucketed Withdrawal Results",
                "db_table": "bucketed_withdrawal_result",
                "ordering": ["calculation", "year"],
            },
        ),
        migrations.AddIndex(
            model_name="withdrawalbucket",
            index=models.Index(
                fields=["scenario"], name="withdrawal__scenari_be66be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="withdrawalbucket",
            index=models.Index(fields=["order"], name="withdrawal__order_0d78bf_idx"),
        ),
        migrations.AddIndex(
            model_name="bucketedwithdrawalresult",
            index=models.Index(
                fields=["calculation", "year"], name="bucketed_wi_calcula_77c7cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bucketedwithdrawalresult",
            index=models.Index(
                fields=["bucket"], name="bucketed_wi_bucket__146d9e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bucketedwithdrawalresult",
            unique_together={("calculation", "year")},
        ),
    ]
