# Generated by Django 5.0.1 on 2025-12-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scenarios", "0002_alter_retirementscenario_calculator_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="retirementscenario",
            name="social_security_claiming_age",
            field=models.IntegerField(
                choices=[
                    (62, "62 (Reduced benefit)"),
                    (65, "65 (Partial benefit)"),
                    (67, "67 (Full Retirement Age)"),
                    (70, "70 (Delayed benefit)"),
                ],
                default=67,
                help_text="Age at which user will claim Social Security",
            ),
        ),
    ]
