# Generated by Django 5.0.1 on 2025-12-18 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scenarios", "0003_retirementscenario_social_security_claiming_age"),
    ]

    operations = [
        migrations.CreateModel(
            name="SensitivityAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "return_adjustment",
                    models.FloatField(
                        default=0.0,
                        help_text="Adjustment to return rate (e.g., -0.02 for -2%)",
                    ),
                ),
                (
                    "spending_adjustment",
                    models.FloatField(
                        default=0.0,
                        help_text="Adjustment to spending (e.g., 0.20 for +20%)",
                    ),
                ),
                (
                    "inflation_adjustment",
                    models.FloatField(
                        default=0.0,
                        help_text="Adjustment to inflation rate (e.g., 0.01 for +1%)",
                    ),
                ),
                ("return_range_min", models.FloatField(default=-0.05)),
                ("return_range_max", models.FloatField(default=0.05)),
                ("return_step", models.FloatField(default=0.01)),
                ("spending_range_min", models.FloatField(default=0.0)),
                ("spending_range_max", models.FloatField(default=0.5)),
                ("spending_step", models.FloatField(default=0.1)),
                ("inflation_range_min", models.FloatField(default=0.0)),
                ("inflation_range_max", models.FloatField(default=0.04)),
                ("inflation_step", models.FloatField(default=0.01)),
                ("result_data", models.JSONField(default=dict)),
                ("execution_time_ms", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensitivity_analyses",
                        to="scenarios.retirementscenario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sensitivity Analysis",
                "verbose_name_plural": "Sensitivity Analyses",
                "db_table": "sensitivity_analysis",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["scenario"], name="sensitivity_scenari_5b134e_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="sensitivity_created_47d1ab_idx"
                    ),
                ],
            },
        ),
    ]
