# Generated by Django 5.0.1 on 2025-12-18 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scenarios", "0004_sensitivityanalysis"),
    ]

    operations = [
        migrations.CreateModel(
            name="WithdrawalStrategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "strategy_type",
                    models.CharField(
                        choices=[
                            ("taxable_first", "Taxable First"),
                            (
                                "tax_deferred_first",
                                "Tax-Deferred First (401k/Traditional IRA)",
                            ),
                            ("roth_first", "Roth First"),
                            ("optimized", "Optimized (Minimize Taxes)"),
                            ("custom", "Custom"),
                        ],
                        default="optimized",
                        max_length=20,
                    ),
                ),
                (
                    "taxable_percentage",
                    models.FloatField(
                        default=0.0,
                        help_text="Percentage of withdrawal from taxable accounts (0.0-1.0)",
                    ),
                ),
                (
                    "traditional_percentage",
                    models.FloatField(
                        default=0.0,
                        help_text="Percentage from Traditional IRA/401k (0.0-1.0)",
                    ),
                ),
                (
                    "roth_percentage",
                    models.FloatField(
                        default=0.0, help_text="Percentage from Roth accounts (0.0-1.0)"
                    ),
                ),
                (
                    "hsa_percentage",
                    models.FloatField(
                        default=0.0, help_text="Percentage from HSA (0.0-1.0)"
                    ),
                ),
                (
                    "preserve_roth_growth",
                    models.BooleanField(
                        default=True,
                        help_text="Preserve Roth accounts for tax-free growth (delay Roth withdrawals)",
                    ),
                ),
                (
                    "minimize_social_security_taxation",
                    models.BooleanField(
                        default=False,
                        help_text="Minimize taxable income to reduce Social Security taxation",
                    ),
                ),
                ("result_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawal_strategies",
                        to="scenarios.retirementscenario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Withdrawal Strategy",
                "verbose_name_plural": "Withdrawal Strategies",
                "db_table": "withdrawal_strategy",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaxEstimate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(help_text="Retirement year (1, 2, 3...)")),
                ("age", models.IntegerField(help_text="User age in this year")),
                (
                    "gross_withdrawal",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total gross withdrawal from all accounts",
                        max_digits=12,
                    ),
                ),
                (
                    "taxable_withdrawal",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Withdrawal from taxable accounts",
                        max_digits=12,
                    ),
                ),
                (
                    "tax_deferred_withdrawal",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Withdrawal from Traditional IRA/401k (fully taxable)",
                        max_digits=12,
                    ),
                ),
                (
                    "roth_withdrawal",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Withdrawal from Roth accounts (tax-free)",
                        max_digits=12,
                    ),
                ),
                (
                    "hsa_withdrawal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Withdrawal from HSA (tax-free if for medical expenses)",
                        max_digits=12,
                    ),
                ),
                (
                    "ordinary_income",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Ordinary income (from tax-deferred accounts, pensions, etc.)",
                        max_digits=12,
                    ),
                ),
                (
                    "capital_gains_income",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Long-term capital gains (from taxable accounts)",
                        max_digits=12,
                    ),
                ),
                (
                    "social_security_taxable",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Portion of Social Security benefits that is taxable (0-85%)",
                        max_digits=12,
                    ),
                ),
                (
                    "agi",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Adjusted Gross Income",
                        max_digits=12,
                    ),
                ),
                (
                    "magi",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Modified Adjusted Gross Income (for Medicare/NIIT)",
                        max_digits=12,
                    ),
                ),
                (
                    "federal_tax",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Federal income tax liability",
                        max_digits=12,
                    ),
                ),
                (
                    "state_tax",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="State income tax liability",
                        max_digits=12,
                    ),
                ),
                (
                    "niit_tax",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Net Investment Income Tax (3.8% on investment income)",
                        max_digits=12,
                    ),
                ),
                (
                    "medicare_surcharge",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Medicare IRMAA surcharge based on MAGI",
                        max_digits=12,
                    ),
                ),
                (
                    "total_tax",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total tax liability for the year",
                        max_digits=12,
                    ),
                ),
                (
                    "effective_tax_rate",
                    models.FloatField(help_text="Effective tax rate (total_tax / agi)"),
                ),
                (
                    "after_tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="After-tax withdrawal amount available for spending",
                        max_digits=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax_estimates",
                        to="scenarios.retirementscenario",
                    ),
                ),
                (
                    "withdrawal_strategy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tax_estimates",
                        to="scenarios.withdrawalstrategy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tax Estimate",
                "verbose_name_plural": "Tax Estimates",
                "db_table": "tax_estimate",
                "ordering": ["scenario", "year"],
            },
        ),
        migrations.AddIndex(
            model_name="withdrawalstrategy",
            index=models.Index(
                fields=["scenario"], name="withdrawal__scenari_2ff457_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="withdrawalstrategy",
            index=models.Index(
                fields=["strategy_type"], name="withdrawal__strateg_f1b450_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="withdrawalstrategy",
            index=models.Index(
                fields=["created_at"], name="withdrawal__created_31a09f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taxestimate",
            index=models.Index(
                fields=["scenario", "year"], name="tax_estimat_scenari_0d3db3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taxestimate",
            index=models.Index(
                fields=["withdrawal_strategy"], name="tax_estimat_withdra_2259b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taxestimate",
            index=models.Index(fields=["age"], name="tax_estimat_age_ef3770_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="taxestimate",
            unique_together={("scenario", "year")},
        ),
    ]
