# Generated by Django 5.0.1 on 2025-12-24 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scenarios", "0005_add_tax_aware_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="withdrawalbucket",
            name="end_age",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="withdrawalbucket",
            name="start_age",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=5, null=True
            ),
        ),
    ]
